"""Abstract floral composition with colorful dahlias, roses, and peonies in thick smoke, with dark moody colors, an ethereal and soft lighting, a dreamy atmosphere, and a surrealistic style, black background , Floating flowers in an artistic photography, elegant and delicate.
"A mesmerizing time-lapse of the Milky Way moving gracefully over a remote desert landscape, showcasing natural rock formations illuminated by starlight."
"A close-up of a beautiful, intricate spider web covered in dew drops, glistening in the morning sunlight, with a soft, blurred background of green foliage."
"A stunning aerial view of a vibrant coral reef teeming with colorful fish and other marine life, set against a backdrop of crystal-clear turquoise waters and white sandy beaches."
"A breathtaking shot of a majestic waterfall cascading down a lush, green mountainside, with mist rising from the base of the falls and a rainbow forming in the spray."
"A serene and tranquil scene of a misty forest at dawn, with sunlight filtering through the trees and casting long shadows on the forest floor, creating a magical and ethereal atmosphere."
"A dramatic and moody black-and-white photograph of a lone figure standing on a rocky cliff overlooking a stormy sea, with crashing waves and dark clouds in the background."
"A whimsical and enchanting image of a fairy-tale castle perched on a hilltop, surrounded by rolling green hills and colorful wildflowers, with a rainbow arching across the sky."
"A surreal and editorial-style conceptual image featuring multiple floating heads of the same woman, suspended in mid-air against a clean, neutral gray background. Each head displays a distinct emotion: joy, sadness, anger, and apathy.The heads are evenly spaced and naturally floating, with realistic shadows and depth, ensuring they blend seamlessly with the background. The lighting is soft and professional, casting gentle shadows that emphasize the contours of the face.
"The woman has long dark hair, red lipstick, and minimal but elegant makeup. Her expressions are clearly defined, capturing strong emotional contrast. The overall composition is visually balanced, ensuring a modern and surreal fashion-inspired aesthetic"
"A vibrant and colorful abstract painting featuring bold, geometric shapes and swirling patterns in a rainbow of hues. The composition is dynamic and energetic, with a sense of movement and rhythm that draws the viewer's eye across the canvas."
A cinematic drone shot revealing a medieval chapel emerging from dense fog, evoking mystery and timelessness.
"A striking and powerful image of a lone wolf standing on a rocky outcrop, silhouetted against a dramatic sunset sky. The wolf's fur is sleek and glossy, and its eyes gleam with intelligence and intensity."
"A peaceful and serene landscape photograph of a tranquil lake surrounded by lush green forests and snow-capped mountains, with a clear blue sky overhead and the sun setting in the distance."
"You hold trust, creativity, and the power to make someone feel their absolute best."
"A stunning and ethereal image of a lone figure standing on a rocky cliff overlooking a vast, misty valley, with the sun setting in the distance and casting a warm, golden light over the landscape."
"A captivating and dreamy photograph of a lone figure walking through a misty forest at dawn, with sunlight filtering through the trees and casting long shadows on the forest floor, creating a magical and ethereal atmosphere."
"A monk inside a wooden basket being hoisted up a steep cliffside by a pulley system. The rope creaks ominously as the wind blows through the misty, towering rock formations."""

landscape = [
    "remote desert landscape",
    "lush, green mountainside",
    "misty forest at dawn",
    "rolling green hills",
    "tranquil lake surrounded by lush green forests and snow-capped mountains",
    "remote desert landscape illuminated by starlight",
    "vibrant coral reef teeming with marine life",
    "majestic waterfall cascading down a mountainside",
    "misty forest at dawn with sunlight filtering through the trees",
    "rolling green hills with a castle",
    "tranquil lake surrounded by forests and mountains",
    "rocky cliff overlooking a stormy sea",
    "hilltop with colorful wildflowers and a rainbow",
    "vast, misty valley with the sun setting",
    "dense fog revealing a medieval chapel",
    "rocky outcrop silhouetted against a sunset sky",
    "snow-covered pine forest",
    "sunset over a serene beach",
    "autumn forest with falling leaves",
    "tropical rainforest with dense foliage",
    "rolling sand dunes in a vast desert",
    "icy tundra with a clear blue sky",
    "mountain range with snow-capped peaks",
    "lush vineyard in the countryside",
    "bamboo forest with sunlight filtering through",
    "savannah with acacia trees and wildlife",
    "rocky canyon with a winding river",
    "picturesque village in the Alps",
    "coastal cliffs with crashing waves",
    "meadow filled with wildflowers",
    "foggy marshland at dawn",
]

subject = [
    "a colorful field of yellow daisies",
    "a colorful field of peonies",
    "a colorful field of dahlias",
    "a colorful field of roses",
    "a colorful field of tulips",
    "a colorful field of sunflowers",
    "a colorful field of poppies",
    "a colorful field of lavender",
    "a colorful field of wildflowers",
    "a colorful field of daffodils",
    "a colorful field of lilies",
    "a colorful field of hydrangeas",
    "a colorful field of orchids",
    "a colorful field of chrysanthemums",
    "a colorful field of irises",
    "a colorful field of carnations",
    "a colorful field of peonies and roses",
    "a colorful field of dahlias and tulips",
    "a colorful field of sunflowers and poppies",
    "a colorful field of lavender and wildflowers",
    "a colorful field of daffodils and lilies",
    "a colorful field of hydrangeas and orchids",
    "a colorful field of chrysanthemums and irises",
    "a colorful field of carnations and peonies",
    "a colorful field of roses and tulips",
    "a colorful field of dahlias and poppies",
    "a colorful field of sunflowers and wildflowers",
    "a colorful field of lavender and daffodils",
    "a colorful field of lilies and hydrangeas",
    "a colorful field of orchids and chrysanthemums",
    "a colorful field of irises and carnations",
    "a colorful field of peonies and roses and tulips",
    "a colorful field of dahlias and sunflowers and poppies",
    "Milky Way",
    "majestic waterfall",
    "lone figure",
    "medieval castle",
    "lone wolf",
    "beautiful, intricate spider web",
    "lone figure standing on a rocky cliff",
    "figure walking through a misty forest",
    "figure standing on a rocky cliff overlooking a valley",
    "vibrant and colorful abstract painting",
    "lone wolf standing on a rocky outcrop",
    "figure standing on a rocky cliff overlooking a misty valley",
    "figure walking through a misty forest at dawn",
    "medieval chapel emerging from dense fog",
]

lighting = [
    "ethereal and soft lighting",
    "sunlight filtering through the trees",
    "starlight",
    "morning sunlight",
    "mist rising from the base of the falls",
    "soft and professional lighting",
    "warm, golden light",
    "golden hour lighting",
    "soft, diffused lighting",
    "moonlit night",
    "glowing embers",
    "twilight glow",
    "harsh midday sun",
    "gentle candlelight",
    "neon lights",
    "lantern-lit",
    "dappled sunlight through leaves",
    "soft moonlight casting gentle shadows",
    "golden rays of dawn breaking through",
    "cool, ambient lighting from bioluminescent plants",
    "flickering torchlight in a dark cave",
    "radiant beams from a lighthouse",
    "soft glow of fireflies in the night",
    "subtle glimmer of distant stars",
    "warm glow of a setting sun",
    "crisp, clear light of a winter morning",
    "gentle illumination from a full moon",
    "soft, ambient light from a city skyline",
    "warm, inviting light from a fireplace",
    "cool, blue light of early dawn",
    "soft, pink hues of a sunset",
    "gentle, diffused light through fog",
]

mood = [
    "dark moody colors",
    "dreamy atmosphere",
    "magical and ethereal atmosphere",
    "dramatic and moody",
    "whimsical and enchanting",
    "serene and tranquil",
    "striking and powerful",
    "captivating and dreamy",
    "mysterious and haunting",
    "uplifting and inspirational",
    "melancholic and reflective",
    "joyful and exuberant",
    "tense and suspenseful",
    "peaceful and calming",
    "romantic and passionate",
    "eerie and unsettling",
    "nostalgic and wistful",
    "vibrant and lively",
]

style = [
    "surrealistic style",
    "artistic photography",
    "editorial-style conceptual image",
    "modern and surreal fashion-inspired aesthetic",
    "abstract painting",
    "cinematic drone shot",
    "minimalist design",
    "vintage film aesthetic",
    "impressionist painting",
    "pop art style",
    "baroque art",
    "steampunk theme",
    "futuristic sci-fi",
    "retro 80s vibe",
    "gothic architecture",
    "cubist art",
    "art nouveau",
    "realism",
    "expressionist style",
    "fantasy illustration",
    "street art graffiti",
    "digital glitch art",
    "anime-inspired",
    "watercolor painting",
    "pixel art",
    "noir film style",
]

composition = [
    "Floating flowers",
    "natural rock formations",
    "soft, blurred background of green foliage",
    "crystal-clear turquoise waters and white sandy beaches",
    "rainbow forming in the spray",
    "long shadows on the forest floor",
    "crashing waves and dark clouds",
    "rainbow arching across the sky",
    "realistic shadows and depth",
    "dynamic and energetic",
    "medieval chapel emerging from dense fog",
    "silhouetted against a dramatic sunset sky",
    "sun setting in the distance",
    "mist rising from the forest floor",
    "sunbeams breaking through the clouds",
    "waves gently lapping at the shore",
    "snowflakes falling softly",
    "leaves rustling in the wind",
    "stars twinkling in the night sky",
    "fog rolling over the hills",
    "sunset reflecting on the water",
    "shadows dancing on the walls",
    "birds soaring in the sky",
    "mountains towering in the distance",
    "flowers blooming in the meadow",
    "trees swaying in the breeze",
    "moonlight casting a glow",
    "clouds drifting across the sky",
    "mist enveloping the landscape",
    "sunlight dappling through the leaves",
    "waves crashing against the rocks",
    "fireflies lighting up the night",
    "rain falling gently on the ground",
]
